app_config_keys = [
    'PRICE_AGG_DB_URI',
    'PRICE_AGG_DB_NAME',
    'PRICE_AGG_DB_QUASI_LIVE_COLLECTION',
    'PRICE_AGG_DB_USERNAME',
    'PRICE_AGG_DB_PASSWORD',
    'PRICE_AGG_SOCKET_ADDRESS',
]

broker_config_keys = [
    'PRICE_AGG_{}_USERNAME',
    'PRICE_AGG_{}_PASSWORD'
]
